// SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
//
// SPDX-License-Identifier: Apache-2.0

import englishMessages from 'ra-language-english';

import * as autogenerated from './en/autogenerated.json';
import * as fields from './en/fields.json';
import * as pages from './en/pages.json';
import * as resources from './en/resources.json';
import * as specs from './en/specs.json';
import * as csv from './en/csv.json';
import * as states from './en/states.json';
import * as messages from './en/messages.json';
import * as actions from './en/actions.json';

const auto =
    autogenerated && 'default' in autogenerated
        ? (autogenerated['default'] as any)
        : autogenerated;

const auto_fields = auto && 'fields' in auto ? auto['fields'] : {};
const user_fields =
    fields && 'default' in fields ? (fields['default'] as any) : fields;
const auto_specs = auto && 'specs' in auto ? auto['specs'] : {};
const user_specs =
    specs && 'default' in specs ? (specs['default'] as any) : specs;

const translations = {
    ...englishMessages,
    fields: { ...auto_fields, ...user_fields },
    specs: { ...auto_specs, ...user_specs },
    resources:
        resources && 'default' in resources ? resources['default'] : resources,
    pages: pages && 'default' in pages ? pages['default'] : pages,
    csv: csv && 'default' in csv ? csv['default'] : csv,
    states: states && 'default' in states ? states['default'] : states,
    messages:
        messages && 'default' in messages ? messages['default'] : messages,
    actions: actions && 'default' in actions ? actions['default'] : actions,
};

export default translations;
